#ifndef CGAMEEFFECT_H_
#define CGAMEEFFECT_H_

#define CGAMEEFFECT_PANIC 24
#define CGAMEEFFECT_POISON 25
#define CGAMEEFFECT_SLEEP 39
#define CGAMEEFFECT_DISEASE 78
#define CGAMEEFFECT_FATIGUE 93
#define CGAMEEFFECT_PROTECTION_FROM_CREATURE 109
#define CGAMEEFFECT_POWER_WORD_SLEEP 217

#endif /* CGAMEEFFECT_H_ */
